// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfzhqwvaehewhbejvkhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmemhxd3ZhZWhld2hiZWp2a2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzY5ODcsImV4cCI6MjA2OTExMjk4N30.miRku_Dpsmx3w7Rj55s5z3KC6XPLu4P372nekJ8jvX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});