// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfohtqfscwwnzjtfrlae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmb2h0cWZzY3d3bnpqdGZybGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTcyODcsImV4cCI6MjA3MTUzMzI4N30.XG5UeJqZ1x9rN6JxhdQkxF8tKRchahjDfOm3jafyq9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});